format = """
$directory\
$git_branch$git_status\
$cmd_duration\
$line_break\
$character"""
add_newline = false
[directory]
format             = "[󰉋 $path]($style)"
style              = "bold #cdd6f4"
truncation_length  = 1
truncation_symbol  = ""
truncate_to_repo   = false
home_symbol        = "~"
read_only          = " 󰌾"
[git_branch]
format = "[ 󰘬 $branch]($style)"
symbol = ""
style  = "#6c7086"
[git_status]
format     = "[$all_status$ahead_behind]($style)"
style      = "#6c7086"
ahead      = " ↑${count}"
behind     = " ↓${count}"
diverged   = " "
modified   = " "
staged     = " "
untracked  = " "
conflicted = " "
deleted    = " "
renamed    = " "
stashed    = " 󰆼"
[cmd_duration]
format   = "[ 󱦟 $duration]($style)"
style    = "#6c7086"
min_time = 5_000
[character]
success_symbol = "[╰─❯](bold #cdd6f4)"
error_symbol   = "[╰─❯](bold #f38ba8)"
vimcmd_symbol  = "[╰─❮](bold #6c7086)"
[package]
disabled = true
[nodejs]
disabled = true
[python]
disabled = true
[golang]
disabled = true
[rust]
disabled = true
[java]
disabled = true
[ruby]
disabled = true
[swift]
disabled = true
[bun]
disabled = true
[conda]
disabled = true
[docker_context]
disabled = true
[jobs]
disabled = true
[status]
disabled = true
[time]
disabled = true
[username]
disabled = true
[hostname]
disabled = true
